name: Abacaxi

options:
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

packages:
  NetworkInterfaces:
    path: Modules/NetworkInterfaces
  Network:
    path: Modules/Network
  GeneralInterfaces:
    path: Modules/GeneralInterfaces
  DomainInterfaces:
    path: Modules/DomainInterfaces
  Domain:
    path: Modules/Domain
  DataInterfaces:
    path: Modules/DataInterfaces
  Data:
    path: Modules/Data
  Launcher:
    path: Modules/Launcher
  Home:
    path: Modules/Home
  PersistenceInterfaces:
    path: Modules/PersistenceInterfaces
  Persistence:
    path: Modules/Persistence
  DesignSystem:
    path: Modules/DesignSystem
  Extensions:
    path: Modules/Extensions
  Recipe:
    path: Modules/Recipe

targetTemplates:
  AbacaxiAppTarget:
    type: application
    platform: iOS
    sources:
      - path: Abacaxi/Sources
      - path: Abacaxi/Resources/Info.plist
        buildPhase: none
      - path: Abacaxi/Resources/Assets.xcassets
        buildPhase: resources
    dependencies:
      - package: NetworkInterfaces
      - package: Network
      - package: GeneralInterfaces
      - package: DomainInterfaces
      - package: Domain
      - package: DataInterfaces
      - package: Data
      - package: Launcher
      - package: Home
      - package: PersistenceInterfaces
      - package: Persistence
      - package: DesignSystem
      - package: Extensions
      - package: Recipe

  ModuleUnitTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      GENERATE_INFOPLIST_FILE: YES

targets:
  Abacaxi:
    templates: [AbacaxiAppTarget]
    configFiles:
      Debug: Configs/Targets/Abacaxi.xcconfig
      Release: Configs/Targets/Abacaxi.xcconfig

  Abacaxi Stage:
    templates: [AbacaxiAppTarget]
    configFiles:
      Debug: Configs/Targets/Abacaxi-Stage.xcconfig
      Release: Configs/Targets/Abacaxi-Stage.xcconfig

  DataTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/Data/Tests, name: DataTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies:
      - package: Data
      - package: DataInterfaces
      - package: NetworkInterfaces
      - package: PersistenceInterfaces

  DataInterfacesTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/DataInterfaces/Tests, name: DataInterfacesTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies: [{package: DataInterfaces}]

  DesignSystemTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/DesignSystem/Tests, name: DesignSystemTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies: [{package: DesignSystem}]

  DomainTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/Domain/Tests, name: DomainTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies:
      - package: Domain
      - package: DataInterfaces
      - package: DomainInterfaces

  DomainInterfacesTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/DomainInterfaces/Tests, name: DomainInterfacesTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies: [{package: DomainInterfaces}]

  GeneralInterfacesTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/GeneralInterfaces/Tests, name: GeneralInterfacesTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies: [{package: GeneralInterfaces}]

  HomeTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/Home/Tests, name: HomeTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies:
      - package: Home
      - package: DomainInterfaces
      - package: GeneralInterfaces

  LauncherTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/Launcher/Tests, name: LauncherTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies:
      - package: Launcher
      - package: DomainInterfaces
      - package: GeneralInterfaces

  NetworkTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/Network/Tests, name: NetworkTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies:
      - package: Network
      - package: NetworkInterfaces

  NetworkInterfacesTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/NetworkInterfaces/Tests, name: NetworkInterfacesTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies: [{package: NetworkInterfaces}]

  PersistenceTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/Persistence/Tests, name: PersistenceTests, group: Test Targets, createIntermediateGroups: false}]
    testHost: PersistenceTestHost
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.abacaxi.persistence-tests
      CODE_SIGN_ENTITLEMENTS: Configs/Tests/PersistenceTests.entitlements
    dependencies:
      - target: PersistenceTestHost
      - package: Persistence
      - package: PersistenceInterfaces

  PersistenceTestHost:
    type: application
    platform: iOS
    sources:
      - path: Configs/Tests/PersistenceTestHost/Sources
      - path: Configs/Tests/PersistenceTestHost/Info.plist
        buildPhase: none
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.abacaxi.persistence-test-host
      CODE_SIGN_ENTITLEMENTS: Configs/Tests/PersistenceTestHost.entitlements

  PersistenceInterfacesTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/PersistenceInterfaces/Tests, name: PersistenceInterfacesTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies: [{package: PersistenceInterfaces}]

  RecipeTests:
    templates: [ModuleUnitTests]
    sources: [{path: Modules/Recipe/Tests, name: RecipeTests, group: Test Targets, createIntermediateGroups: false}]
    dependencies: [{package: Recipe}]

schemes:
  AllTests:
    build:
      targets:
        DataInterfacesTests: [test]
        DataTests: [test]
        DesignSystemTests: [test]
        DomainInterfacesTests: [test]
        DomainTests: [test]
        GeneralInterfacesTests: [test]
        HomeTests: [test]
        LauncherTests: [test]
        NetworkInterfacesTests: [test]
        NetworkTests: [test]
        PersistenceInterfacesTests: [test]
        PersistenceTests: [test]
        RecipeTests: [test]
    test:
      gatherCoverageData: true
      targets:
        - DataInterfacesTests
        - DataTests
        - DesignSystemTests
        - DomainInterfacesTests
        - DomainTests
        - GeneralInterfacesTests
        - HomeTests
        - LauncherTests
        - NetworkInterfacesTests
        - NetworkTests
        - PersistenceInterfacesTests
        - PersistenceTests
        - RecipeTests
  DataTests: {build: {targets: {DataTests: [test]}}, test: {gatherCoverageData: true, targets: [DataTests]}}
  DataInterfacesTests: {build: {targets: {DataInterfacesTests: [test]}}, test: {gatherCoverageData: true, targets: [DataInterfacesTests]}}
  DesignSystemTests: {build: {targets: {DesignSystemTests: [test]}}, test: {gatherCoverageData: true, targets: [DesignSystemTests]}}
  DomainTests: {build: {targets: {DomainTests: [test]}}, test: {gatherCoverageData: true, targets: [DomainTests]}}
  DomainInterfacesTests: {build: {targets: {DomainInterfacesTests: [test]}}, test: {gatherCoverageData: true, targets: [DomainInterfacesTests]}}
  GeneralInterfacesTests: {build: {targets: {GeneralInterfacesTests: [test]}}, test: {gatherCoverageData: true, targets: [GeneralInterfacesTests]}}
  HomeTests: {build: {targets: {HomeTests: [test]}}, test: {gatherCoverageData: true, targets: [HomeTests]}}
  LauncherTests: {build: {targets: {LauncherTests: [test]}}, test: {gatherCoverageData: true, targets: [LauncherTests]}}
  NetworkTests: {build: {targets: {NetworkTests: [test]}}, test: {gatherCoverageData: true, targets: [NetworkTests]}}
  NetworkInterfacesTests: {build: {targets: {NetworkInterfacesTests: [test]}}, test: {gatherCoverageData: true, targets: [NetworkInterfacesTests]}}
  PersistenceTests: {build: {targets: {PersistenceTests: [test]}}, test: {gatherCoverageData: true, targets: [PersistenceTests]}}
  PersistenceInterfacesTests: {build: {targets: {PersistenceInterfacesTests: [test]}}, test: {gatherCoverageData: true, targets: [PersistenceInterfacesTests]}}
  RecipeTests: {build: {targets: {RecipeTests: [test]}}, test: {gatherCoverageData: true, targets: [RecipeTests]}}
